### ISSUE TITLE
Cross domain sessions

### ISSUE THREAD

**Issue by billdami** [tihomir-kit/sesior#1]
Trying to follow your example application in order to get sessions working in my express/socket.io app, but I am having a bit of trouble, and I think the culprit is a cross-domain issue. I am serving my app on heroku as two distinct apps, one serving the static assets for an ember.js single-page application, and ther other handling API requests, via an api.myapp.com subdomain.

When I browse to my client application, I am getting "Not authorized" errors, which indicate that the session isn't being created by the initial ajax request that socket.io sends before switching over to a WebSocket connection. However if I first make a request to api.myapp.com via a new browser tab, and then open the client app, I don't get any errors.

Is there any additional configuration I need to do on the server or client side in order to allow the session to be initialized via that initial CORS ajax request made by socket.io?

**Comment by tihomir-kit** [comment]
Hi billdami,

I am not sure if this will help, but on client, in AngularJS [$http](https://docs.angularjs.org/api/ng/service/$http) requests, I used `withCredentials` property set to `true`. Like this for example:

``` js
this.registerUser = function (userName) {
    $http.post(RouteService.node.register, { userName: userName }, { withCredentials: true })
        .success(function (data) {
            if (data.membershipResolved) {
                initializeSocketIo(data.user);
                initializeCurrentUser(data.user);
            }
            else {
                console.log("An error occured while trying to register " + userName);
            }
        })
        .error(function () {
            console.log("An error occured while trying to register " + userName);
        });
};
```

which works with `"Access-Control-Allow-Credentials"` from the backend middleware:

``` js
var allowCrossDomain = function (req, res, next) {
    res.header("Access-Control-Allow-Origin", config.allowedCORSOrigins);
    res.header("Access-Control-Allow-Methods", "GET,PUT,POST,DELETE");
    res.header("Access-Control-Allow-Headers", "Content-Type");
    res.header("Access-Control-Allow-Credentials", "true");
    next();
};
```

check if that helps. And I guess you most probably did it, but I'll ask anyway, just in case - did you setup the [config.js](https://github.com/pootzko/sesior/blob/master/SESIOR.Node/config.js)?

Let me know if the `withCredentials` fix helped.

Cheers.

**Comment by billdami** [comment]
Yep, that was the issue. Essentially I was not making a regular REST ajax request to my api server before the socket.io connection was established (my application does not require authentication, just persistent sessions, thats why there was none). But once I added that ajax request with `withCredentials: true`, the session was successfully created, and the socket.io connection was able to access it.

A bit of a follow-up question on this though if you don't mind; Would there be any way to get around having to fire off that preemptive ajax REST request to initiate the session cookie? In other words, let the socket.io connection be in charge of setting up the session which standard express routes could then access, instead of the other way around? While I'm not that experienced with socket.io, it seems like it would be technically possible, since socket.io always initiates a connection via a standard XHR request, before switching over to WebSocket transport.

While its not essential, I think in my case it would be a bit cleaner (and would remove the need for that initial XHR request whose only purpose is to start the session), since my application is really much more socket focused, and the standard express routes are secondary.

Thanks for all your help!

**Comment by tihomir-kit** [comment]
Hi, I'm glad it helped! :)

I'm really not sure about your second question.. If it's doable I can definitely see how it might be very tricky to pull off. 

I personally wouldn't consider the preemptive request to be that "dirty" as it will most probably pay off in the future. You can simply view it as a very cheap initialization.

If you try and make it work the other way around, let us know how. :)

Cheers.
