### ISSUE TITLE
Routes and socket.io

### ISSUE THREAD

**Issue by aHumanBeing** [tihomir-kit/sesior#2]
Hi,

How does this behave with accessing routes?  For example, I am not using socket.io together with the session and for each route I access, the socket disconnects and reconnects with a new socket id.  I'm trying to find a solution where I can keep the socket id or have the socket work off of usernames some how.

Why do I need this?  Basically, users perform certain actions in my web app and other users may need to contact them from any route.  I can't accomplish this if the socket id always changes.  Additionally, a user may login more than once (using multiple browsers).

Thanks

**Comment by tihomir-kit** [comment]
Hi,

well, if you have a full page reload, there is no way of going around the reconnection. If you're using a SPA framework (such as AngularJS) then you shouldn't have problems with this as the connection will remain open all the time. 

If he reconnects, other users that are in the "same chat" need to be notified of his new session Id. I haven't played with persisting session Id in that sense. I'm not even sure if you can set it or whether you get assigned a session Id by the server.

I also didn't think (or need) logging in from multiple places at once, so I don't have any advice about that, sorry.. :/

**Comment by aHumanBeing** [comment]
Understood.  If I manage a solution I'll post it here for others to look over. Thanks for getting back to me anyway :)

**Comment by tihomir-kit** [comment]
Ok, thnx. :)
