### ISSUE TITLE
Using socket id instead of username

### ISSUE THREAD

**Issue by aHumanBeing** [tihomir-kit/sesior#3]
Hi,

Would I be able to apply this concept where I use the socket id instead of username for the handshake?  In my web application, a user may login several times (on different machines) thus, in Redis, they would have several entries (each having their own session id as the key name).

Thank you

**Comment by tihomir-kit** [comment]
Hi,

yes, I believe that would work if the session Id exists "soon enough" in the whole cycle - that's the only thing I'm not sure about from the top of my head.. But you should be able to test this easily enough, simply change a few variables and see if it works.

**Comment by aHumanBeing** [comment]
Thanks for the quick response!  I'll give it a shot.

**Comment by tihomir-kit** [comment]
No problem, cheers.
